// Generated by scripts/gen-types.ts from spec/api/*.schema.json. Do not edit.

export interface ChangeEvent {
  provider: string
  root: string
  id?: string | null
  slug?: string | null
  parentId?: string | null
  [k: string]: unknown
}

export interface Dashboard {
  schemaVersion: 1
  id: string
  name: string
  title: string
  createdAt: number
  endedAt?: number
  sources: {
    key: string
    socket?: string
    session?: string
    title?: string
    [k: string]: unknown
  }[]
  control: string | null
  [k: string]: unknown
}

export interface Handoff {
  id: string
  filename: string
  file: string
  bytes: number
  history: {
    complete: boolean
    warnings: {
      code: string
      conversationId?: string
      parentConversationId?: string
      sourceSessionId?: string
      status?: number
      [k: string]: unknown
    }[]
    conversations: number
    messages: number
    [k: string]: unknown
  }
  state: 'exported' | 'dispatching' | 'launched' | 'unknown'
  terminal: TerminalEntry | null
  error: string | null
  target: {
    provider: string
    root: string
    rootLabel?: string
    [k: string]: unknown
  } | null
  [k: string]: unknown
}

export interface TerminalEntry {
  key: string
  provider?: string
  root?: string
  id?: string | null
  slug?: string | null
  cwd?: string | null
  title?: string | null
  launchId?: string | null
  port?: number
  pid?: number
  url?: string
  name?: string
  socket?: string
  attached?: boolean
  tmux?: boolean
  startedAt?: (string | number) | null
  [k: string]: unknown
}

export interface HomeReport {
  scope: {
    sources: {
      provider: string
      root: string
      rootLabel?: string
      [k: string]: unknown
    }[]
    errors: {
      [k: string]: unknown
    }[]
    [k: string]: unknown
  }
  errors: {
    provider?: string
    root?: string
    error: string
    [k: string]: unknown
  }[]
  notices: {
    message: string
    [k: string]: unknown
  }[]
  capturedAt: number
  sources?: {
    provider: string
    root: string
    rootLabel?: string
    [k: string]: unknown
  }[]
  totals?: {
    [k: string]: unknown
  }
  coverage?: {
    [k: string]: unknown
  }
  folders?: {
    [k: string]: unknown
  }[]
  activity?: {
    [k: string]: unknown
  }
  entries?: {
    [k: string]: unknown
  }[]
  nextCursor?: string | null
  [k: string]: unknown
}

export interface Project {
  slug: string
  cwd: string | null
  sessionCount: number
  lastActivity: (string | number) | null
  [k: string]: unknown
}

export interface Root {
  id: string
  label: string
  dir: string
  exists?: boolean
  [k: string]: unknown
}

export interface SessionSummary {
  id: string
  title?: string | null
  firstPrompt: string
  lastUserPrompt: string
  lastUserPromptTs: (string | number) | null
  firstTs: (string | number) | null
  lastTs: (string | number) | null
  cwd?: string | null
  userTurns: number
  assistantTurns: number
  toolCalls: number
  models: string[]
  toolCounts: {
    [k: string]: number
  }
  tokens: {
    input: number
    output: number
    cacheRead: number
    cacheCreate?: number
    total: number
    reasoning?: number
    [k: string]: unknown
  }
  contextWindow?: number | null
  lastTokenUsage?: {
    [k: string]: unknown
  } | null
  rateLimits?: {
    [k: string]: unknown
  } | null
  hasSubagents?: boolean
  isSubagent?: boolean
  [k: string]: unknown
}

export interface Target {
  provider?: string | null
  root?: string | null
  rootLabel?: string | null
  slug?: string | null
  id?: string | null
  cwd?: string | null
  title?: string | null
  project?: string | null
  launchId?: string | null
  terminalKey?: string | null
  view?: string | null
  kind?: string | null
  dashboardId?: string | null
  draft?: boolean
  homeScope?: {
    excluded: string[]
    excludedRoots?: string[]
    [k: string]: unknown
  }
  homeSource?: {
    provider: string
    root: string
    rootLabel?: string
    [k: string]: unknown
  } | null
  focus?: {
    id?: string
    slug?: string
    [k: string]: unknown
  } | null
  [k: string]: unknown
}

export interface TimelineEvent {
  kind: 'user' | 'assistant' | 'system' | 'attachment'
  ts?: (string | number) | null
  text?: string
  uuid?: string
  subtype?: string | null
  model?: string | null
  usage?: {
    [k: string]: unknown
  } | null
  parts?: (TextPart | ThinkingPart | ToolCallPart | AdvisorPart)[]
  [k: string]: unknown
}

export interface TextPart {
  kind: 'text'
  text: string
  [k: string]: unknown
}

export interface ThinkingPart {
  kind: 'thinking'
  text: string
  [k: string]: unknown
}

export interface ToolCallPart {
  kind: 'tool_call'
  id?: string | null
  name: string
  input?: unknown
  result?: {
    content?: unknown
    isError?: boolean
    meta?: {
      [k: string]: unknown
    } | null
    [k: string]: unknown
  } | null
  isError?: boolean
  [k: string]: unknown
}

export interface AdvisorPart {
  kind: 'advisor'
  text: string
  [k: string]: unknown
}

export interface Usage {
  root?: string
  rateLimits: {
    [k: string]: unknown
  } | null
  sessionId: string | null
  ts: number | null
  contextWindow?: {
    [k: string]: unknown
  } | null
  groups?: {
    [k: string]: unknown
  }[]
  [k: string]: unknown
}
