#!/usr/bin/env node
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'
import { compileFromFile } from 'json-schema-to-typescript'

// Compile referenced/nested named declarations too, then deduplicate identical
// declarations. Omitting them left TimelineEvent.parts referring to missing
// names, which skipLibCheck could silently treat as unchecked types.
export async function generateDeclarations(directory: string) {
  const names = (await fs.readdir(directory)).filter((name) => name.endsWith('.schema.json')).sort()
  const compiled = await Promise.all(
    names.map((name) =>
      compileFromFile(path.join(directory, name), {
        bannerComment: '',
        declareExternallyReferenced: true,
        unknownAny: true,
        style: { singleQuote: true, semi: false, printWidth: 140, tabWidth: 2 },
      })
    )
  )
  const declarations = new Map()
  for (const text of compiled) {
    const source = ts.createSourceFile('contracts.d.ts', text, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
    for (const statement of source.statements) {
      if (!ts.isInterfaceDeclaration(statement) && !ts.isTypeAliasDeclaration(statement)) throw Error('Unexpected generated declaration kind')
      const name = statement.name.text,
        declaration = statement.getText(source)
      if (declarations.has(name) && declarations.get(name) !== declaration) throw Error(`Conflicting generated declarations: ${name}`)
      declarations.set(name, declaration)
    }
  }
  return {
    count: names.length,
    output: '// Generated by scripts/gen-types.ts from spec/api/*.schema.json. Do not edit.\n\n' + [...declarations.values()].join('\n\n') + '\n',
  }
}

async function main() {
  const root = fileURLToPath(new URL('../', import.meta.url))
  const { count, output } = await generateDeclarations(path.join(root, 'spec/api'))
  const destination = path.join(root, 'shared/types.d.ts')
  if (process.argv.includes('--check')) {
    const current = await fs.readFile(destination, 'utf8').catch(() => '')
    if (current !== output) throw new Error('Generated contracts are stale; run npm run gen:types')
    console.log('gen-types: ' + count + ' schemas, declarations current')
  } else {
    await fs.writeFile(destination, output)
    console.log('gen-types: ' + count + ' schemas -> shared/types.d.ts')
  }
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main()
